### ISSUE TITLE
Build error on windows with Qt 5.9

### ISSUE THREAD

**Issue by CarlSandstrom** [vsg-dev/vsgQt#19]
When compiling under Windows 10 with Qt 5.9 I get a build error:

\home\carl\tmp\vsg\vsgQt\src\vsgQt\ViewerWindow.cpp(188): error C2039: 'cout': is not a member of 'std' [C:\cygwin64\home\carl\tmp\vsg\build\src\vsgQt\vsgQt.vcxproj]

If I add #include \<iostream\> to ViewerWindow.cpp, it compiles correctly and my test program successfully displays my 3d models. 

(Note that I build from the command line in cygwin in order to get VulkanSceneGrapch and vsgQt into our development environment)

**Comment by robertosfield** [comment]
Sorry didn't spot this as have a newer Qt version installed. Could you try updating as I've checked in a fix: ab8ec504833313f4390eb50029c173c0687b8aee

**Comment by CarlSandstrom** [comment]
It works fine now!
