### ISSUE TITLE
I have already set up glslang when building VSG, why do I still encounter errors?

### ISSUE THREAD

**Issue by Idealist-dreamer** [vsg-dev/vsgQt#37]
![问题1](https://github.com/user-attachments/assets/26ef32f4-8c2c-4212-9a5c-ddbc5d61bff9)
![问题2](https://github.com/user-attachments/assets/a2db8b77-e143-415c-8ea5-a0c4df8eeca4)

**Comment by robertosfield** [comment]
This is a VSG Issue rather than a vsgQt one, why are you posting this here?

As for the Issue itself, could it be that you have an version of glslang that is too old? i.e. older than 14.0?
