### ISSUE TITLE
OK?

### ISSUE THREAD

**Issue by suchaoyong** [vsg-dev/vsgQt#38]
vsgQt，

KeyBoardMap.cpp, line 233,    "   ... >='A' ||   ... >='Z'  ...   "

Window.h, line 74, _initialized = false ;    never come to true;

**Comment by robertosfield** [comment]
Thanks for the note, issue now fixed:

05cb1ff52c98d79e643a7d0d755f63f14aa9aec9

In future could you provide more helpful title and contents as it was rather cryptic, I had to review the code to figure out what you might be referring to.
