### ISSUE TITLE
C# winform with vsg

### ISSUE THREAD

**Issue by XMatrixXiang** [vsg-dev/vsgQt#40]
A long time ago, I wrote a Demo for the integration of OSG and MFC. At that time, the approach was to transmit the handle of the MFC window to OSG, and then open a separate thread in OSG for rendering. Now I plan to try the integration of vsg and C# winform. If I pass the handle of C# window to vsg and then let vsg render in an independent thread alone, I don't know if this method is feasible.

**Comment by robertosfield** [comment]
Did you mean to post this here?  It's not vsgQt issue and this is the vsgQt issue tracker.  

Perhaps post a question to the VSG discussion forum?  To see if other Windows can provide some guidance.

**Comment by XMatrixXiang** [comment]
> Did you mean to post this here? It's not vsgQt issue and this is the vsgQt issue tracker.
> 
> Perhaps post a question to the VSG discussion forum? To see if other Windows can provide some guidance.

I am very sorry. It is indeed not suitable to initiate this issue here. I will close it right away.
