### ISSUE TITLE
Build failure on Windows with Qt 5.11

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgQt#9]
I recently updated the vsgQt source code and tried to build this source code using MinGW and Qt5.11, which resulted in a build failure.

[_log.txt](https://github.com/vsg-dev/vsgQt/files/7242847/_log.txt)
```
[   92s] /home/abuild/rpmbuild/BUILD/vsgQt-0.0.0+20210924+git.1cbfcc2/src/vsgQt/ViewerWindow.cpp: In member function 'void vsgQt::ViewerWindow::intializeUsingVSGWindow(uint32_t, uint32_t)':
[   92s] /home/abuild/rpmbuild/BUILD/vsgQt-0.0.0+20210924+git.1cbfcc2/src/vsgQt/ViewerWindow.cpp:198:40: error: 'xcb_window_t' does not name a type
[   92s]   198 |     traits->nativeWindow = static_cast<xcb_window_t>(winId());
[   92s]       |                                        ^~~~~~~~~~~~ 
```
I read on https://groups.google.com/g/vsg-users/c/-GBJDJUdBGw/m/njvRgHcmAQAJ that some changes were made to support Qt < 5.10, but it looks like the changes also prevent building for Qt > 5.10. The question here is if is this change also required for Qt 5.11 or only for Qt5.10 ? In the latter case, I think this should be included only when using Qt5.10.

**Comment by robertosfield** [comment]
Ooops... That's unix specific cast in there.  This will need replacing with  platform specific #ifdef's with each block passing the appropriate type.  I am in the middle of set of changes to the core VSG, no unrelated to the vsgQt functionality, but once I've got what I want to change working and checked in I'll pop back over to vsgQt and have bash at adding Windows and macOS appropriate casts.

**Comment by robertosfield** [comment]
@rhabacker  rather than wait for my other work to be fully bedded down, I've revert my other changes to vsgQt and checked in just the change that should fix the build:

[#4c6c6ffa750c473e0eb5b3d59de7dbf550a398a90](https://github.com/vsg-dev/vsgQt/commit/c6c6ffa750c473e0eb5b3d59de7dbf550a398a90)

This should get things compiling, but the vsg::Window::create(traits); won't yet work inheriting the QWindow's platform specific window into the vsg::Win32_Window/MacOS_Window implementation as only the Xcb_Window supports native Window inheritance.  I only just added the Xcb support at the end of last week, but as I don't have Windows or macOS I can't complete this work  - and will need others under Windows and macOS to implement the required changes and test it,

**Comment by rhabacker** [comment]
There is still an build error: 
```
[   56s] /home/abuild/rpmbuild/BUILD/vsgQt-0.0.0+20210928+git.44c4aab/src/vsgQt/ViewerWindow.cpp: In member function 'void vsgQt::ViewerWindow::intializeUsingVSGWindow(uint32_t, uint32_t)':
[   56s] /home/abuild/rpmbuild/BUILD/vsgQt-0.0.0+20210928+git.44c4aab/src/vsgQt/ViewerWindow.cpp:199:53: error: invalid static_cast from type 'WId' {aka 'unsigned int'} to type 'HWND' {aka 'HWND__*'}
[   56s]   199 |     traits->nativeWindow = static_cast<HWND>(winId());
[   56s]       |                                                     ^
[   56s] make[2]: *** [src/vsgQt/CMakeFiles/vsgQt.dir/build.make:112: src/vsgQt/CMakeFiles/vsgQt.dir/ViewerWindow.cpp.obj] Error 1
```
According to https://stackoverflow.com/questions/37187060/why-is-this-an-error-static-castunsignedi the use of `static_cast` is not allowed here

**Comment by robertosfield** [comment]
On Tue, 28 Sept 2021 at 15:44, Ralf Habacker ***@***.***>
wrote:

> There is still an build error:
>
> [   56s] /home/abuild/rpmbuild/BUILD/vsgQt-0.0.0+20210928+git.44c4aab/src/vsgQt/ViewerWindow.cpp: In member function 'void vsgQt::ViewerWindow::intializeUsingVSGWindow(uint32_t, uint32_t)':
> [   56s] /home/abuild/rpmbuild/BUILD/vsgQt-0.0.0+20210928+git.44c4aab/src/vsgQt/ViewerWindow.cpp:199:53: error: invalid static_cast from type 'WId' {aka 'unsigned int'} to type 'HWND' {aka 'HWND__*'}
> [   56s]   199 |     traits->nativeWindow = static_cast<HWND>(winId());
> [   56s]       |                                                     ^
> [   56s] make[2]: *** [src/vsgQt/CMakeFiles/vsgQt.dir/build.make:112: src/vsgQt/CMakeFiles/vsgQt.dir/ViewerWindow.cpp.obj] Error 1
>
> According to
> https://stackoverflow.com/questions/37187060/why-is-this-an-error-static-castunsignedi
> the use of static_cast is not allowed here
>

To get things compiling just comment out this line, it's a precursor
getting vsg::Win32_Windpw.cpp updated so it can inherit the native
windowing from the one created by Qt.  We'll need to find another way of
converting the winId() to the appropriate Windows specific window type.

Happy to take suggestions.

Robert.

**Comment by robertosfield** [comment]
I've looked at discussions online and followed the headers to see what types in play are.  My best guess is that a reintrepret_cast<HWMD> would be the appropriate thing to use under Windows as HWMD looks to be a pointer.  I've checked this change in. @rhabacker  could you test it?

2908ed216fc3e40ddd7b3dd4efcbd275bf25e8c1

**Comment by rhabacker** [comment]
It builds now, thanks for your support,
